In [7]:
import pandas as pd
import akshare as ak
import talib

stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="300750", period="daily", start_date="19900101", end_date='21000101', adjust="qfq")
fund_etf_hist_em_df = ak.fund_etf_hist_em(symbol="159915", period="daily", start_date="20000101", end_date="21000101", adjust="qfq")

stock_zh_a_hist_df_s=stock_zh_a_hist_df[stock_zh_a_hist_df["日期"]>pd.to_datetime("2020-01-01")]
fund_etf_hist_em_df_s = fund_etf_hist_em_df[pd.to_datetime(fund_etf_hist_em_df["日期"])>pd.to_datetime("2020-01-01")]

fund_etf_hist_em_df_s["日期"] = pd.to_datetime(fund_etf_hist_em_df_s["日期"])
stock_zh_a_hist_df_s["日期"] = pd.to_datetime(stock_zh_a_hist_df_s["日期"])
merge_stock_zh_df = pd.merge(stock_zh_a_hist_df_s[["日期", "涨跌幅"]], fund_etf_hist_em_df_s[["日期", "涨跌幅"]], how="inner", on="日期")

# 填充缺失值为上一条记录的涨跌幅
merge_stock_zh_df["涨跌幅_x"].fillna(method="ffill", inplace=True)
merge_stock_zh_df["涨跌幅_y"].fillna(method="ffill", inplace=True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_5124\3399917921.py:8: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  stock_zh_a_hist_df_s=stock_zh_a_hist_df[stock_zh_a_hist_df["日期"]>pd.to_datetime("2020-01-01")]
C:\Users\Administrator\AppData\Local\Temp\ipykernel_5124\3399917921.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fund_etf_hist_em_df_s["日期"] = pd.to_datetime(fund_etf_hist_em_df_s["日期"])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_5124\3399917921.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_zh_a_hist_df_s["日期"] = pd.to_datetime(stock_zh_a_hist_df_s["日期"])

In [2]:
merge_stock_zh_df

            日期  涨跌幅_x  涨跌幅_y
0   2021-01-04  15.65   3.84
1   2021-01-05  -0.54   0.40
2   2021-01-06   1.22   0.50
3   2021-01-07   1.64   1.76
4   2021-01-08  -2.18  -0.65
..         ...    ...    ...
847 2024-07-05  -1.10   0.43
848 2024-07-08  -0.96  -1.66
849 2024-07-09  -0.08   1.50
850 2024-07-10  -1.55  -0.12
851 2024-07-11   2.29   2.22

[852 rows x 3 columns]

In [8]:
index = talib.CORREL(merge_stock_zh_df["涨跌幅_x"], merge_stock_zh_df["涨跌幅_y"], timeperiod=5)
index

0            NaN
1            NaN
2            NaN
3            NaN
4      -0.518053
          ...
1090   -0.333168
1091    0.146182
1092    0.079767
1093    0.201063
1094    0.753755
Length: 1095, dtype: float64

In [9]:
beta_df = pd.DataFrame(index)
beta_df["日期"]=merge_stock_zh_df["日期"]
merge_stock_zh_df_1 = pd.merge(merge_stock_zh_df, beta_df, how="inner")
merge_stock_zh_df_1

             日期  涨跌幅_x  涨跌幅_y         0
0    2020-01-02   1.21   2.02       NaN
1    2020-01-03   2.13  -0.06       NaN
2    2020-01-06  -0.46   1.36       NaN
3    2020-01-07  -0.62   1.90       NaN
4    2020-01-08   1.15  -1.65 -0.518053
...         ...    ...    ...       ...
1090 2024-07-05  -1.10   0.43 -0.333168
1091 2024-07-08  -0.96  -1.66  0.146182
1092 2024-07-09  -0.08   1.50  0.079767
1093 2024-07-10  -1.55  -0.12  0.201063
1094 2024-07-11   2.29   2.22  0.753755

[1095 rows x 4 columns]