In [6]:
import akshare as ak

stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="300750", period="daily", start_date="19900101", end_date='21000101', adjust="qfq")
stock_zh_a_hist_df

,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,2018-06-11,9.64,12.99,12.99,9.64,788,2.845471e+06,48.98,89.91,6.15,0.04
1,2018-06-12,15.00,15.00,15.00,15.00,266,1.058375e+06,0.00,15.47,2.01,0.01
2,2018-06-13,17.21,17.21,17.21,17.21,450,1.972314e+06,0.00,14.73,2.21,0.02
3,2018-06-14,19.64,19.64,19.64,19.64,743,3.578184e+06,0.00,14.12,2.43,0.03
4,2018-06-15,22.32,22.32,22.32,22.32,2565,1.359503e+07,0.00,13.65,2.68,0.12
...,...,...,...,...,...,...,...,...,...,...,...
1473,2024-07-05,181.00,177.62,182.49,176.50,135247,2.414694e+09,3.34,-1.10,-1.98,0.35
1474,2024-07-08,176.01,175.91,178.37,175.01,108064,1.907514e+09,1.89,-0.96,-1.71,0.28
1475,2024-07-09,175.30,175.77,177.30,173.09,164439,2.876833e+09,2.39,-0.08,-0.14,0.42
1476,2024-07-10,175.01,173.05,180.09,173.05,177729,3.123227e+09,4.01,-1.55,-2.72,0.46
1477,2024-07-11,175.00,177.01,178.98,173.49,208111,3.678618e+09,3.17,2.29,3.96,0.53

In [8]:
import akshare as ak

fund_etf_hist_em_df = ak.fund_etf_hist_em(symbol="159915", period="daily", start_date="20000101", end_date="21000101", adjust="qfq")

fund_etf_hist_em_df

,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,2011-12-09,0.795,0.797,0.814,0.795,1061772,8.514398e+07,2.35,-1.60,-0.013,0.33
1,2011-12-12,0.790,0.790,0.803,0.790,311065,2.485670e+07,1.63,-0.88,-0.007,0.10
2,2011-12-13,0.788,0.768,0.788,0.763,967444,7.452749e+07,3.16,-2.78,-0.022,0.30
3,2011-12-14,0.768,0.760,0.777,0.755,816095,6.282018e+07,2.86,-1.04,-0.008,0.25
4,2011-12-15,0.755,0.752,0.764,0.747,417005,3.137289e+07,2.24,-1.05,-0.008,0.13
...,...,...,...,...,...,...,...,...,...,...,...
3051,2024-07-05,1.615,1.623,1.630,1.601,8138205,1.313878e+09,1.79,0.43,0.007,2.54
3052,2024-07-08,1.615,1.596,1.620,1.592,7936130,1.273748e+09,1.73,-1.66,-0.027,2.47
3053,2024-07-09,1.594,1.620,1.629,1.584,11008810,1.768441e+09,2.82,1.50,0.024,3.43
3054,2024-07-10,1.609,1.618,1.636,1.608,7768890,1.262057e+09,1.73,-0.12,-0.002,2.42
3055,2024-07-11,1.640,1.654,1.664,1.627,9657457,1.590536e+09,2.29,2.22,0.036,3.01

In [13]:
import pandas as pd

stock_zh_a_hist_df_s=stock_zh_a_hist_df[stock_zh_a_hist_df["日期"]>pd.to_datetime("2021-01-01")]
fund_etf_hist_em_df_s = fund_etf_hist_em_df[pd.to_datetime(fund_etf_hist_em_df["日期"])>pd.to_datetime("2021-01-01")]
fund_etf_hist_em_df_s

C:\Users\Administrator\AppData\Local\Temp\ipykernel_16436\3611624397.py:3: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  stock_zh_a_hist_df_s=stock_zh_a_hist_df[stock_zh_a_hist_df["日期"]>pd.to_datetime("2021-01-01")]
C:\Users\Administrator\AppData\Local\Temp\ipykernel_16436\3611624397.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fund_etf_hist_em_df_s["日期"] = pd.to_datetime(fund_etf_hist_em_df_s["日期"])

,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
2204,2021-01-04,2.864,2.976,2.990,2.861,2472764,7.278150e+08,4.50,3.84,0.110,0.77
2205,2021-01-05,2.940,2.988,2.997,2.925,2470004,7.346481e+08,2.42,0.40,0.012,0.77
2206,2021-01-06,3.000,3.003,3.030,2.953,2290438,6.844461e+08,2.58,0.50,0.015,0.71
2207,2021-01-07,2.996,3.056,3.056,2.978,2029990,6.118732e+08,2.60,1.76,0.053,0.63
2208,2021-01-08,3.065,3.036,3.086,3.011,1867431,5.666295e+08,2.45,-0.65,-0.020,0.58
...,...,...,...,...,...,...,...,...,...,...,...
3051,2024-07-05,1.615,1.623,1.630,1.601,8138205,1.313878e+09,1.79,0.43,0.007,2.54
3052,2024-07-08,1.615,1.596,1.620,1.592,7936130,1.273748e+09,1.73,-1.66,-0.027,2.47
3053,2024-07-09,1.594,1.620,1.629,1.584,11008810,1.768441e+09,2.82,1.50,0.024,3.43
3054,2024-07-10,1.609,1.618,1.636,1.608,7768890,1.262057e+09,1.73,-0.12,-0.002,2.42
3055,2024-07-11,1.640,1.654,1.664,1.627,9657457,1.590536e+09,2.29,2.22,0.036,3.01

In [15]:
fund_etf_hist_em_df_s["日期"] = pd.to_datetime(fund_etf_hist_em_df_s["日期"])
stock_zh_a_hist_df_s["日期"] = pd.to_datetime(stock_zh_a_hist_df_s["日期"])
merge_stock_zh_df = pd.merge(stock_zh_a_hist_df_s[["日期", "涨跌幅"]], fund_etf_hist_em_df_s[["日期", "涨跌幅"]], how="inner", on="日期")
merge_stock_zh_df

C:\Users\Administrator\AppData\Local\Temp\ipykernel_16436\900226770.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fund_etf_hist_em_df_s["日期"] = pd.to_datetime(fund_etf_hist_em_df_s["日期"])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_16436\900226770.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_zh_a_hist_df_s["日期"] = pd.to_datetime(stock_zh_a_hist_df_s["日期"])

            日期  涨跌幅_x  涨跌幅_y
0   2021-01-04  15.65   3.84
1   2021-01-05  -0.54   0.40
2   2021-01-06   1.22   0.50
3   2021-01-07   1.64   1.76
4   2021-01-08  -2.18  -0.65
..         ...    ...    ...
847 2024-07-05  -1.10   0.43
848 2024-07-08  -0.96  -1.66
849 2024-07-09  -0.08   1.50
850 2024-07-10  -1.55  -0.12
851 2024-07-11   2.29   2.22

[852 rows x 3 columns]